Sync with skeleton.sh

diff --git a/check_unattended_upgrades b/check_unattended_upgrades
--- a/check_unattended_upgrades
+++ b/check_unattended_upgrades
@@ -75,38 +75,17 @@
 # (seconds).
 #CHECK_WARNING=93600
 
+
+FIRST_RELEASE=2015-04-25
+VERSION=1.0
 PROJECT_PAGES='https://github.com/JosefFriedrich-shell/check_unattended_upgrades
 https://exchange.icinga.com/joseffriedrich/check_unattended_upgrades
 https://exchange.nagios.org/directory/Plugins/Software/check_unattended_upgrades/details'
-
 SHORT_DESCRIPTION='Monitoring plugin to check automatic updates (unattended-upgrades) on Debian / Ubuntu.'
-
-# Exit codes
-STATE_OK=0
-STATE_WARNING=1
-STATE_CRITICAL=2
-STATE_UNKNOWN=3
-
-_get_config() {
-	eval $(apt-config shell "$2" "$1")
-}
-
-_check_config() {
-	local CONFIG=$1
-	local DEBIT=$2
-
-	_get_config $CONFIG "CREDIT"
-	if [ "$DEBIT" != "$CREDIT" ]; then
-			echo "CRITICAL - The configuration '$CONFIG' is not configured properly. It has the value '$CREDIT', but it should have '$DEBIT'."
-		exit $STATE_CRITICAL
-	fi
-}
-
-_usage() {
-  echo "check_unattended_upgrades
+USAGE="check_unattended_upgrades v$VERSION
 Copyright (c) 2015 Josef Friedrich <jf@josef-friedrich.de>
 
-This plugin checks if automatic updates (unattended_upgrades) are working.
+$SHORT_DESCRIPTION
 
 
 Usage: check_unattended_upgrades <options>
@@ -148,7 +127,29 @@ Options:
     Time interval since the last execution to result in a warning state
     (seconds).
 "
+
+# Exit codes
+STATE_OK=0
+STATE_WARNING=1
+STATE_CRITICAL=2
+STATE_UNKNOWN=3
+
+_get_config() {
+	eval $(apt-config shell "$2" "$1")
 }
+
+_check_config() {
+	local CONFIG=$1
+	local DEBIT=$2
+
+	_get_config $CONFIG "CREDIT"
+	if [ "$DEBIT" != "$CREDIT" ]; then
+			echo "CRITICAL - The configuration '$CONFIG' is not configured properly. It has the value '$CREDIT', but it should have '$DEBIT'."
+		exit $STATE_CRITICAL
+	fi
+}
+
+## This SEPARATOR is required for test purposes. Please don’t remove! ##
 
 while getopts ":a:Ac:d:e:hl:m:r:Rs:Su:w:" OPT; do
 	case $OPT in
@@ -173,7 +174,7 @@ while getopts ":a:Ac:d:e:hl:m:r:Rs:Su:w:" OPT; do
 			;;
 
 		h)
-			_usage
+			echo "$USAGE"
 			exit 0
 			;;
 
