Check the last log line for ERROR and WARNING messages #3

diff --git a/check_unattended_upgrades b/check_unattended_upgrades
--- a/check_unattended_upgrades
+++ b/check_unattended_upgrades
@@ -358,12 +358,24 @@ if ! test -f $LOG_FILE ; then
 	exit $STATE_CRITICAL
 fi
 
-LAST_LOG_LINE=$(cat $LOG_FILE | grep -v ' WARNING ' | grep -v ' ERROR ' | tail -n 1)
+LOG_TEXT="$(cat $LOG_FILE)"
 
-if [ -z "$LAST_LOG_LINE" ]; then
+if [ -z "$LOG_TEXT" ]; then
 	LATEST_COMPRESSED_LOG=$(ls -r ${LOG_FILE}.*.gz | tail -n 1)
-	LAST_LOG_LINE=$(zcat $LATEST_COMPRESSED_LOG | tail -n 1)
+	LOG_TEXT="$(zcat $LATEST_COMPRESSED_LOG)"
 fi
+
+if [ -z "$(cat $LOG_TEXT | tail -n 1 | grep -v ' ERROR ')" ]; then
+	echo "CRITICAL - The last line in the log file is an ERROR message."
+	exit $STATE_CRITICAL
+fi
+
+if [ -z "$(cat $LOG_TEXT | tail -n 1 | grep -v ' WARNING ')" ]; then
+	echo "WARNING - The last line in the log file is a WARNING message."
+	exit $STATE_WARNING
+fi
+
+LAST_LOG_LINE="$(cat $LOG_TEXT | grep -v ' WARNING ' | grep -v ' ERROR ' | tail -n 1)"
 
 LAST_RUN_DATE=$(echo $LAST_LOG_LINE | cut -d "," -f 1)
 
