Add a check if log file is empty.

diff --git a/check_unattended_upgrades b/check_unattended_upgrades
--- a/check_unattended_upgrades
+++ b/check_unattended_upgrades
@@ -164,18 +164,22 @@ fi
 
 # Log file check
 
-LOG_FILE='/var/log/unattended-upgrades/unattended-upgrades.log'
+LOG_FILE='/var/log/unattended-upgrades/unattended-upgrades-test.log'
 
 if [ ! -f $LOG_FILE ]; then
 	echo "CRITICAL - Log file ($LOG_FILE) does not exist."
 	exit 2
 fi
 
-LAST_RUN_DATE=$(tail -n 1 /var/log/unattended-upgrades/unattended-upgrades.log | cut -d "," -f 1)
+LAST_RUN_DATE=$(tail -n 1 $LOG_FILE | cut -d "," -f 1)
+
+if [ -z "$LAST_RUN_DATE" ]; then
+	echo "CRITICAL - The date on which the command 'unattended-upgrades' ran for the last time, could not be determined. The log file '$LOG_FILE' is empty."
+	exit 2
+fi
+
 LAST_RUN=$(date -d "$LAST_RUN_DATE" +%s)
-
 CURRENT_DATE=$(date +%s)
-
 DIFF=$((CURRENT_DATE - LAST_RUN))
 
 # Critical
